services:
  postgres-db:
    image: postgres:15
    container_name: postgres-container-custom
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data

volumes:
  postgres_data: